server:
  port: 8888

spring:
  application:
    name: pay-assist

  ##rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: pay_guest
    password: pay_guest
    virtual-host: /pay
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

