server:
  port: 8888

spring:
  application:
    name: pay-assist
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

